E,N=set(),set()
n1=int(input('Enter the number of elements in set E: '))
print('Enter the elements of set E:')
for i in range(n1): E.add(int(input()))
n2=int(input('Enter the number of elements in set N: '))
print('Enter the elements of set N:')
for i in range(n2): N.add(int(input()))
print('Union of E and N is',E.union(N))
print('Intersection of E and N is',E.intersection(N))
print('Difference of E and N is',E.difference(N))
print('Symmetric Difference of E and N is',E.symmetric_difference(N))
